In [1]:
import numpy as np


In [83]:
# part a
D = np.random.rand(3,2)
print(D)

U,S,V = np.linalg.svd(D,full_matrices=False)
np.allclose(D, np.dot(U * S, V))
np.allclose(D,np.dot(U,np.dot(np.diag(L),V)))

S[2:]=0.
newD = np.dot(U,np.dot(np.diag(S),V))
print(newD)
print('Reconstructed original data!')

[[0.84548717 0.22952799]
 [0.80040351 0.03801875]
 [0.30960235 0.1206228 ]]
[[0.84548717 0.22952799]
 [0.80040351 0.03801875]
 [0.30960235 0.1206228 ]]
Reconstructed original data!


In [84]:
# part b
C2 = np.dot(np.transpose(D),D)
C3 = np.dot(D,np.transpose(D))
print('Covariance matrix 2x2: '+str(C2))
print('Covariance matrix 3x3: '+str(C3))

W2,U2 = np.linalg.eig(C2)
print('Eigenvalues of 2x2: '+str(W2))
print('Eigenvectors of 2x2: ' +str(U2))

W3,U3 = np.linalg.eig(C3)
print('Eigenvalues of 3x3: '+str(W3))
print('Eigenvectors of 3x3: ' +str(U3))

Cnew2 = np.dot(U2,np.dot(np.diag(W2),np.transpose(U2)))
Cnew3 = np.dot(U3,np.dot(np.diag(W3),np.transpose(U3)))
print('New Cov Matrix 2x2: '+str(Cnew2))
print('New Cov Matrix 3x3: '+str(Cnew3))
print('Reconstructed Covariance!')
#U,S,V = np.linalg.eig(D,full_matrices=False)
#np.allclose(D, np.dot(U * S, V))
#np.allclose(D,np.dot(U,np.dot(np.diag(L),V)))

#S[2:]=0.
#newD = np.dot(U,np.dot(np.diag(S),V))
#print(newD)

Covariance matrix 2x2: [[1.45134795 0.26183841]
 [0.26183841 0.06867838]]
Covariance matrix 3x3: [[0.76753165 0.68545727 0.28945112]
 [0.68545727 0.64209121 0.25239273]
 [0.28945112 0.25239273 0.11040347]]
Eigenvalues of 2x2: [1.49927167 0.02075466]
Eigenvectors of 2x2: [[ 0.98365981 -0.18003714]
 [ 0.18003714  0.98365981]]
Eigenvalues of 3x3: [1.49927167e+00 2.07546600e-02 2.31848009e-17]
Eigenvectors of 3x3: [[-0.7129708  -0.51059229 -0.48059145]
 [-0.64859421  0.74067264  0.17529856]
 [-0.26645485 -0.43669159  0.85924517]]
New Cov Matrix 2x2: [[1.45134795 0.26183841]
 [0.26183841 0.06867838]]
New Cov Matrix 3x3: [[0.76753165 0.68545727 0.28945112]
 [0.68545727 0.64209121 0.25239273]
 [0.28945112 0.25239273 0.11040347]]
Reconstructed Covariance!
